; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
src_dir = ./
[env:genericSTM32F103RC]
platform = ststm32
board = genericSTM32F103RC
; framework = stm32cube
monitor_speed = 115200
custom_prog_version = 0.0.1
platform_packages =
    toolchain-gccarmnoneeabi@1.140201.0
extra_scripts = 
        add_newlibnano.py 
        pre:export_hex.py
build_flags =
        -DVERSION=${this.custom_prog_version}
        -DU8G2_ENABLED
        -Wl,-u_printf_float         
        -D STM32F103xE
        -D LV_LVGL_H_INCLUDE_SIMPLE
        -I "Core/Inc"
        -I "Drivers/CMSIS/Include"
        -I "Drivers/CMSIS/Device/ST/STM32F1xx/Include"
        -I "Drivers/STM32F1xx_HAL_Driver/Inc"
        -I "Drivers/STM32F1xx_HAL_Driver/Inc/Legacy"
        -I "Lib"
        -I "Lib/sht3x"
        -I "Lib/w25qxx"
        -I "Lib/crc8"
        -I "Lib/i2cdev"
        -I "Lib/key"
        -I "Lib/lis2dh12"
        -I "Lib/littlefs"
        -I "Lib/m24cxx"
        -I "Lib/mpu6050"
        -I "Lib/oled"
        -I "Lib/spibus"
        -I "Lib/u8g2"
        -I "App"
        -I "FreeRTOS/include"
        -I "FreeRTOS/port/GCC/ARM_CM3"
        -I "FreeRTOS"
        ; -I "LVGL"
        ; -I "LVGL/examples/porting"
        ; -I "LVGL/src"
        ; -I "LVGL/demos"

build_src_filter =
        +<startup_stm32f103xe.s>
        +<Core/Src> 
        +<Drivers/> 
        +<Lib/>
        ; -<Lib/mpu6050>
        ; -<Lib/oled>
        ; -<Lib/u8g2>
        +<App/>
        +<FreeRTOS/>
        ; +<LVGL/>    ; LVGL 模式时启用

board_build.ldscript = STM32F103XX_FLASH.ld
upload_protocol = serial
upload_port = COM4
upload_speed = 115200
upload_flags = -i rts,-dtr,-rts
debug_tool = stlink

