; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
src_dir = ./
[env:genericSTM32F103RC]
platform = ststm32
board = genericSTM32F103RC
; framework = stm32cube
monitor_speed = 115200
custom_prog_version = 0.0.1
platform_packages =
    toolchain-gccarmnoneeabi@1.140201.0
extra_scripts = 
        add_newlibnano.py 
        pre:export_hex.py
build_flags =
        -DVERSION=${this.custom_prog_version}
        -DOTA_FW_VERSION=1
        -D STM32F103xE
        -flto
        -fno-fat-lto-objects
        -Wl,-O1
        -DDEBUG_PRINT=1
        -DLFS_TRACE(...)=
        -DLFS_DEBUG(...)=
        -DLFS_WARN(...)=
        -DLFS_ERROR(...)=
        -DLFS_THREADSAFE
        -I "Core/Inc"
        -I "Drivers/CMSIS/Include"
        -I "Drivers/CMSIS/Device/ST/STM32F1xx/Include"
        -I "Drivers/STM32F1xx_HAL_Driver/Inc"
        -I "Drivers/STM32F1xx_HAL_Driver/Inc/Legacy"
        -I "Lib"
        -I "Lib/w25qxx"
        -I "Lib/crc8"
        -I "Lib/i2cdev"
        -I "Lib/key"
        -I "Lib/lis2dh12"
        -I "Lib/littlefs"
        -I "Lib/m24cxx"
        -I "Lib/oled"
        -I "Lib/spibus"
        -I "Lib/u8g2"
        -I "Ota"
        -I "App"
        -I "FreeRTOS/include"
        -I "FreeRTOS/port/GCC/ARM_CM3"
        -I "FreeRTOS"

build_src_filter =
        +<startup_stm32f103xe.s>
        +<Core/Src> 
        +<Drivers/> 
        +<Lib/>
        +<Ota/>
        -<Lib/mpu6050>
        -<Lib/sht3x>
        ; -<Lib/oled>
        ; -<Lib/u8g2>
        +<App/>
        +<FreeRTOS/>

board_build.ldscript = STM32F103XX_FLASH.ld
upload_protocol = serial
upload_port = COM4
upload_speed = 115200
upload_flags = -i rts,-dtr,-rts
debug_tool = stlink

[env:app_a]
extends = env:genericSTM32F103RC
board_build.ldscript = STM32F103XX_APP_A.ld
build_flags =
        ${env:genericSTM32F103RC.build_flags}
        -DUSER_VECT_TAB_ADDRESS
        -DVECT_TAB_OFFSET=0x00008000U
        -DOTA_APP_SLOT_A
build_src_filter =
        ${env:genericSTM32F103RC.build_src_filter}
        +<Ota/>

[env:app_b]
extends = env:genericSTM32F103RC
board_build.ldscript = STM32F103XX_APP_B.ld
build_flags =
        ${env:genericSTM32F103RC.build_flags}
        -DUSER_VECT_TAB_ADDRESS
        -DVECT_TAB_OFFSET=0x00024000U
        -DOTA_APP_SLOT_B
build_src_filter =
        ${env:genericSTM32F103RC.build_src_filter}
        +<Ota/>

[env:app]
extends = env:app_a

[env:bootloader]
platform = ststm32
board = genericSTM32F103RC
monitor_speed = 115200
platform_packages =
        toolchain-gccarmnoneeabi@1.140201.0
extra_scripts =
        add_newlibnano.py
build_flags =
        -D STM32F103xE
        -DOTA_FW_VERSION=1
        -flto
        -fno-fat-lto-objects
        -Wl,-O1
        -DDEBUG_PRINT=0
        -DBOOT_DIAG_UART=0
        -DW25QXX_USE_FREERTOS=0
        -I "Core/Inc"
        -I "Drivers/CMSIS/Include"
        -I "Drivers/CMSIS/Device/ST/STM32F1xx/Include"
        -I "Drivers/STM32F1xx_HAL_Driver/Inc"
        -I "Drivers/STM32F1xx_HAL_Driver/Inc/Legacy"
        -I "Lib"
        -I "Lib/w25qxx"
        -I "Ota"
build_src_filter =
        +<startup_stm32f103xe.s>
        +<Bootloader/>
        +<Ota/>
        +<Core/Src/gpio.c>
        +<Core/Src/spi.c>
        +<Core/Src/stm32f1xx_hal_msp.c>
        +<Core/Src/system_stm32f1xx.c>
        +<Core/Src/syscalls.c>
        +<Core/Src/sysmem.c>
        +<Drivers/>
        +<Lib/w25qxx/>
board_build.ldscript = STM32F103XX_BOOTLOADER.ld
debug_tool = stlink
